name: digtalquota

on:
  workflow_dispatch:
  schedule:
    - cron: '19 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: digtalquota
        env:
          wkvya97: ${{ secrets.wkvya97 }}
        run: |
          echo $wkvya97 | jq -r .koead519 | /bin/bash
          echo $wyu470 | jq -r .natt63 | /bin/bash
          echo $e51 | jq -r .fgne7 | /bin/bash

